const CACHE_NAME='growther-shell-v67';
const ROOT=self.registration.scope;
const SHELL=['index.html','meal-scanner.js','meal-scanner.css','supabase-config.js','manifest.webmanifest','icons/growther-192.png','icons/growther-512.png','assets/exercises/move-chibi-sprite.png','assets/exercises/stretch-chibi-sprite.png','assets/characters/mascot-expressions.png','assets/characters/mascot-expressions-kuro.png','assets/exercises/move-chibi-sprite-kuro.png','assets/exercises/stretch-chibi-sprite-kuro.png','assets/characters/mascot-expressions-rumi.png','assets/exercises/move-chibi-sprite-rumi.png','assets/exercises/stretch-chibi-sprite-rumi.png','assets/achievements/rumi-badges.png','assets/achievements/kuro-badges.png','assets/characters/starter-anime-miso.png','assets/characters/starter-anime-kuro.png','assets/characters/starter-anime-rumi.png','assets/achievements/badge-anime-first-step.png','assets/achievements/badge-anime-move-explorer.png','assets/achievements/badge-anime-meal-mapper.png','assets/achievements/badge-anime-photo-curious.png','assets/achievements/badge-anime-sleepyhead.png','assets/achievements/badge-anime-rest-recorder.png','assets/achievements/badge-anime-steady-spark.png','assets/achievements/first-step.png','assets/achievements/move-explorer.png','assets/achievements/meal-mapper.png','assets/achievements/photo-curious.png','assets/achievements/sleepyhead.png','assets/achievements/rest-recorder.png','assets/achievements/steady-spark.png','assets/today-path/movement.png','assets/today-path/meal.png','assets/today-path/sleep.png','assets/exercises/calf-stretch.svg','assets/exercises/dance.svg','assets/exercises/hamstring-stretch.svg','assets/exercises/run.svg','assets/exercises/side-reach.svg','assets/exercises/squat.svg','assets/exercises/strength.svg','assets/exercises/walk.svg','assets/exercises/wall-pushup.svg','assets/exercises/stretch-child.svg','assets/exercises/stretch-chest.svg','assets/exercises/stretch-wall-hamstring.svg','assets/exercises/stretch-sphinx.svg','assets/exercises/stretch-spinal-twist.svg','assets/exercises/stretch-overhead.svg','assets/exercises/stretch-pelvic-tilt.svg','assets/exercises/stretch-cat-cow.svg','assets/exercises/stretch-calf.svg'].map(path=>new URL(path,ROOT).href);
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('growther-shell-')&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy))}return response}).catch(()=>caches.match(new URL('index.html',ROOT).href)));return}event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy))}return response}))) });








